# Generated by Django 5.0.7 on 2024-11-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_ending',
            field=models.DateField(blank=True, null=True, verbose_name='Date Ending'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_starting',
            field=models.DateField(blank=True, null=True, verbose_name='Date Starting'),
        ),
    ]
