# Generated by Django 5.0.7 on 2024-08-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_surname'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='projects', to='accounts.profile'),
        ),
    ]
