# Generated by Django 5.0.7 on 2024-11-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('M', 'MSC'), ('R', 'RESPONSIBLE COMPUTING')], max_length=1, null=True, verbose_name='Category'),
        ),
    ]
