# Generated by Django 5.0.7 on 2025-02-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='custom_url',
            field=models.URLField(blank=True, help_text='Provide a custom link for the project (optional).', null=True, verbose_name='Custom URL'),
        ),
    ]
