# Generated by Django 5.0.7 on 2024-07-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_created_at_project_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='External Link'),
        ),
    ]
