# Generated by Django 5.0.7 on 2024-08-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Published'),
        ),
    ]
