# Generated by Django 5.0.7 on 2024-11-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Date Published'),
        ),
    ]
