# Generated by Django 5.0.7 on 2024-08-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Cover Image'),
        ),
    ]
