# Generated by Django 5.0.7 on 2024-08-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_basemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
