# Generated by Django 5.0.7 on 2024-08-01 19:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_basemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
