# Generated by Django 5.0.7 on 2024-08-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_basemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Short Description'),
        ),
    ]
