# Generated by Django 5.0.7 on 2024-08-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_basemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Title'),
        ),
    ]
