# Generated by Django 5.0.7 on 2024-08-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_basemodel_slug_alter_basemodel_title'),
        ('core', '0006_basemodel_short_description'),
    ]

    operations = [
    ]
