# Generated by Django 5.0.7 on 2024-07-30 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_basemodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
            ],
            options={
                'verbose_name': 'Outreach',
                'verbose_name_plural': 'Outreaches',
            },
            bases=('core.basemodel',),
        ),
    ]
