# Generated by Django 5.0.7 on 2024-08-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('title', 'first_name', 'last_name')},
        ),
    ]
