# Generated by Django 5.0.7 on 2024-08-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
            ],
            options={
                'verbose_name': 'Robot',
                'verbose_name_plural': 'Robots',
            },
            bases=('core.basemodel',),
        ),
    ]
