# Generated by Django 5.0.7 on 2024-08-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reference')),
                ('document', models.FileField(blank=True, null=True, upload_to=None, verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
            bases=('core.basemodel',),
        ),
    ]
