# Generated by Django 5.0.7 on 2024-07-30 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='publication',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='document',
            field=models.FileField(default='', upload_to=None, verbose_name='Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Reference'),
        ),
    ]
