# Generated by Django 5.0.7 on 2024-08-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='document',
        ),
    ]
