# Generated by Django 5.0.7 on 2024-08-05 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_title_alter_profile_profile_picture'),
        ('publications', '0002_remove_publication_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='accounts.profile'),
            preserve_default=False,
        ),
    ]
