# Generated by Django 5.0.7 on 2024-08-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publication_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='reference',
        ),
    ]
