# Generated by Django 5.0.7 on 2024-08-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_remove_publication_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
    ]
