# Generated by Django 5.0.7 on 2024-08-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_profile_options_profile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('degree', models.CharField(blank=True, max_length=200, null=True, verbose_name='Degree')),
                ('specialty', models.CharField(blank=True, max_length=200, null=True, verbose_name='Specialty')),
                ('pursuing', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pursuing')),
                ('focus', models.CharField(blank=True, max_length=200, null=True, verbose_name='Focus')),
                ('quote', models.TextField(blank=True, null=True, verbose_name='Quote')),
                ('category', models.CharField(blank=True, choices=[('P', 'Postgraduate'), ('U', 'Undergraduate'), ('A', 'Admin'), ('I', 'PI'), ('L', 'Lecturer')], max_length=1, null=True, verbose_name='Category')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
            bases=('accounts.profile',),
        ),
    ]
