# Generated by Django 5.0.7 on 2024-08-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='focus',
        ),
        migrations.AddField(
            model_name='person',
            name='focus_long',
            field=models.TextField(blank=True, null=True, verbose_name='Focus Long'),
        ),
        migrations.AddField(
            model_name='person',
            name='focus_short',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Focus Short'),
        ),
        migrations.AddField(
            model_name='person',
            name='focus_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Focus Title'),
        ),
    ]
