# Generated by Django 5.0.7 on 2024-08-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='degree',
            field=models.TextField(blank=True, null=True, verbose_name='Degree'),
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='person',
            name='focus',
            field=models.TextField(blank=True, null=True, verbose_name='Focus'),
        ),
        migrations.AddField(
            model_name='person',
            name='pursuing',
            field=models.TextField(blank=True, null=True, verbose_name='Pursuing'),
        ),
        migrations.AddField(
            model_name='person',
            name='quote',
            field=models.TextField(blank=True, null=True, verbose_name='Quote'),
        ),
        migrations.AddField(
            model_name='person',
            name='specialty',
            field=models.TextField(blank=True, null=True, verbose_name='Specialty'),
        ),
    ]
