# Generated by Django 5.0.7 on 2024-08-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_person_description_remove_person_focus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='linked_in_link',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile Link'),
        ),
    ]
