# Generated by Django 5.0.7 on 2024-08-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_degree_person_description_person_focus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='person',
            name='focus',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Focus'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pursuing',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pursuing'),
        ),
        migrations.AlterField(
            model_name='person',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Specialty'),
        ),
    ]
