# Generated by Django 5.0.7 on 2024-08-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_person_degree_alter_person_focus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.CharField(blank=True, choices=[('P', 'Postgraduate'), ('U', 'Undergraduate'), ('A', 'Admin'), ('I', 'PI'), ('L', 'Lecturer')], max_length=1, null=True, verbose_name='Category'),
        ),
    ]
