# Generated by Django 5.0.7 on 2024-08-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_person_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(blank=True, choices=[('P', 'Postgraduate'), ('M', 'MSC'), ('U', 'Undergraduate'), ('A', 'Admin'), ('I', 'PI'), ('L', 'Lecturer')], max_length=1, null=True, verbose_name='Category'),
        ),
    ]
