# Generated by Django 5.0.7 on 2024-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(unique=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(unique=True, verbose_name='Response'),
        ),
    ]
